apiVersion: v1
kind: ConfigMap
metadata:
  name: api-bot-helper-function-config-example
  namespace: castai-agent
data:
  function_config.json: |
    {
      "function": {
        "function_name": "example_function",
        "inputs": [
          {
            "name": "param1",
            "value": "default_value1"
          },
          {
            "name": "param2",
            "value": "default_value2"
          }
        ],
        "env_variables": [
          {
            "name": "LOG_LEVEL",
            "value": "INFO"
          }
        ]
      }
    }
