apiVersion: v1
kind: Pod
metadata:
  name: api-helper-bot-pod
  namespace: castai-agent
spec:
  dnsPolicy: ClusterFirst
  priorityClassName: system-cluster-critical
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1003
    runAsGroup: 1003
    runAsNonRoot: true
    runAsUser: 1003
  containers:
  - name: castai-api-bot-helper-container_bare_bones
    image: dancastai/castai_api_bot_helper_bare_bones:0.0.1
    imagePullPolicy: Always
    env:
    - name: CLUSTER_ID
      valueFrom:
        configMapKeyRef:
          key: CLUSTER_ID
          name: castai-cluster-controller
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: castai-hibernate
          key: API_KEY
    - name: ENV_VAR1
      value: "World!"
